export const products = [
  {
    id: 1,
    name: 'Худи с принтом',
    price: 999,
    category: 'hoodie',
    image: 'public/images/hoodie1.jpg',
  },
  {
    id: 2,
    name: 'Черное худи',
    price: 1299,
    category: 'hoodie',
    image: 'public/images/hoodie2.jpeg',
  },
  {
    id: 3,
    name: 'Серое худи',
    price: 1099,
    category: 'hoodie',
    image: 'public/images/hoodie3.jpg',
  },
  {
    id: 4,
    name: 'Худи Oversize',
    price: 1499,
    category: 'hoodie',
    image: 'https://via.placeholder.com/300x300/e0e0e0/333333?text=Худи+4',
  },
  {
    id: 5,
    name: 'Худи с капюшоном',
    price: 1199,
    category: 'hoodie',
    image: 'https://via.placeholder.com/300x300/9e9e9e/ffffff?text=Худи+5',
  },
  {
    id: 6,
    name: 'Худи унисекс',
    price: 1399,
    category: 'hoodie',
    image: 'https://via.placeholder.com/300x300/f0f0f0/333333?text=Худи+6',
  },
  {
    id: 7,
    name: 'Шорты спортивные',
    price: 799,
    category: 'shorts',
    image: 'public/images/shorts.jpg',
  },
  {
    id: 8,
    name: 'Шорты джинсовые',
    price: 1599,
    category: 'shorts',
    image: 'https://via.placeholder.com/300x300/2196f3/ffffff?text=Шорты+2',
  },
  {
    id: 9,
    name: 'Шорты беговые',
    price: 899,
    category: 'shorts',
    image: 'https://via.placeholder.com/300x300/ff9800/ffffff?text=Шорты+3',
  },
  {
    id: 10,
    name: 'Шорты пляжные',
    price: 699,
    category: 'shorts',
    image: 'https://via.placeholder.com/300x300/ffc107/333333?text=Шорты+4',
  },
  {
    id: 11,
    name: 'Шорты с карманами',
    price: 999,
    category: 'shorts',
    image: 'https://via.placeholder.com/300x300/795548/ffffff?text=Шорты+5',
  },
  {
    id: 12,
    name: 'Шорты хлопковые',
    price: 849,
    category: 'shorts',
    image: 'https://via.placeholder.com/300x300/607d8b/ffffff?text=Шорты+6',
  },
];